#!/bin/bash
python3 -c 'print((lambda n:("bestchol"[0] if n==0 else "".join("bestchol"[(n//(8**k))%8] for k in range(int(__import__("math").log(n,8)),-1,-1))))(sum("water".index(c)*(5**i) for i,c in enumerate(reversed(__import__("os").environ["WATER"])))+sum("stir".index(c)*(4**i) for i,c in enumerate(reversed(__import__("os").environ["STIR"]))))'
